version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - ${Port}:${Port} # Assume your Go app runs on port from environment, adjust if necessary
    volumes:
      - .:/app # Optional: Mount the source code into the container for development
      - gopath:/go
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DBUsername}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DATABASE: ${DBName}
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
  gopath: